name: Build and Publish Docker Image

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

env:
  IMAGE_NAME: functionland/loyal-agent  # Name of the Docker Hub repository

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or personal access token stored as a GitHub secret

      # Step 3: Extract metadata for Docker image tags and labels
      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
